name: build & deploy docker container
# run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on:
  push:
    tags:
      - "v*"
env:
  IMAGE_NAME_BACKEND: ${{ secrets.DOCKER_HUB_USERNAME }}/whoami
  CONTAINER_NAME: whoami-test
  DOMAIN_SUFFIX: dev.digitdrop.pl
  SERVICE_NAME_BACKEND: faq-backend
  SERVICE_NAME_FRONTEND: faq
  DESTINATION_STACK_PATH: .

jobs:
  build-backedn-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Debug backend
        run: |
          echo ${{github.ref_name}}
          echo ${{github.trigger_name}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME_BACKEND }}:latest
            ${{ env.IMAGE_NAME_BACKEND }}:${{ github.ref_name }}

  build-frontend-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Debug frontend
        run: |
          echo "frontend"

  deploy-app-on-s1:
    runs-on: self-hosted
    needs: [build-backedn-docker-image, build-frontend-docker-image]
    steps:
      - name: Debug
        run: |
          echo ${{github.ref_name}}
          echo ${{github.trigger_name}}
          id
      - name: Checkout
        uses: actions/checkout@v3

      # - name: Run container
      #   run: |
      #     docker ps
      #     docker version
      #     docker rm -f $CONTAINER_NAME
      #     docker run -d -p 8000:80 --name ${{ env.CONTAINER_NAME }} ${{ env.IMAGE_NAME_BACKEND }}:${{ github.ref_name }}
      #     docker ps

      - name: Deploy  docker stack
        run: |
          envsubst < faq-stack.yml >$DESTINATION_STACK_PATH/faq-deploy.yml
          docker stack deploy -c $DESTINATION_STACK_PATH/faq-deploy.yml faq
          docker ps
