name: ci
run-name: ${{ github.actor }} is running ci jobs
on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

env:
  RELEASE_VER: ${GITHUB_REF#refs/*/}

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{github.ref_name}}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $GITHUB_ENV
          echo $RELEASE_VERSION
          echo $RELEASE_VER

      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/whoami:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/whoami:${{github.ref_name}}

  # ${{ secrets.DOCKER_HUB_USERNAME }}/whoami:$GITHUB_ENV
