name: build image
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on:
  push:
    tags:
      - "v*"
env:
  IMAGE_NAME: ${{ secrets.DOCKER_HUB_USERNAME }}/whoami
  CONTAINER_NAME: whoami-test

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{github.ref_name}}
          echo ${{github.trigger_name}}
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ env.IMAGE_NAME }}:latest
            ${{ env.IMAGE_NAME }}:${{ github.ref_name }}

  deploy-container-on-s1:
    runs-on: [self-hosted, s1]
    steps:
      - name: Debug
        run: |
          echo ${{github.ref_name}}
          echo ${{github.trigger_name}}
      - name: Run container
        run: |
          docker ps
          docker version
          docker rm -f $CONTAINER_NAME
          docker run -d -p 8000:80 ${{ env.IMAGE_NAME }}:${{ github.ref_name }}
          docker ps
