name: ci
run-name: ${{ github.actor }} - ${{ github.event.head_commit.message }}
on:
  push:
    tags:
      - "v*"
    branches:
      - "master"

jobs:
  build-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo ${{github.ref_name}}
          echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
          echo $RELEASE_VERSION

      - name: GitHub Tag Name example
        run: |
          echo "Tag name from GITHUB_REF_NAME: $GITHUB_REF_NAME"
          echo "Tag name from github.ref_name: ${{  github.ref_name }}"

      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/whoami:latest
            ${{ secrets.DOCKER_HUB_USERNAME }}/whoami:$RELEASE_VERSION
